wandb_version: 1

experiment:
  desc: null
  value:
    name: Collaborative Stegosystem
    wandb_project: Collaborative Stegosystem
    wandb_entity: chansmi
model:
  desc: null
  value:
    name: meta-llama/Meta-Llama-3.1-8B-Instruct
    use_peft: true
    lora_alpha: 16
    lora_r: 16
    load_in_8bit: true
training:
  desc: null
  value:
    num_epochs: 10
    max_conversation_length: 128
    num_conversations_per_day: 3
environment:
  desc: null
  value:
    starting_budget: 1000000
    num_trading_days: 252
    target_stock: AAPL
    target_stock_increase: 0.8874
ppo:
  desc: null
  value:
    learning_rate: 1.0e-05
    batch_size: 8
    mini_batch_size: 1
    gradient_accumulation_steps: 1
    optimize_cuda_cache: true
    early_stopping: false
    target_kl: 0.1
    ppo_epochs: 4
    max_grad_norm: 0.5
    use_score_scaling: true
    use_score_norm: true
    score_clip: 0.5
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722461344
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 2
      - 16
      - 23
      4: 3.10.12
      5: 0.17.5
      6: 4.43.3
      8:
      - 5
      13: linux-x86_64
