wandb_version: 1

wandb:
  desc: null
  value:
    project_name: collaborative-stegosystem
    entity: chansmi
env:
  desc: null
  value:
    max_rounds: 10
    stocks:
    - AAPL
    - GOOGL
    - MSFT
    - AMZN
    - FB
    reward:
      correct: 1.0
      partial: 0.5
      incorrect: -0.5
    eve_penalty: 2.0
model:
  desc: null
  value:
    name: meta-llama/Meta-Llama-3.1-8B-Instruct
    quantize: true
    save_path: models/trained_model
    temperature: 0.9
    max_new_tokens: 150
    top_p: 0.9
ppo:
  desc: null
  value:
    learning_rate: 1.0e-05
    batch_size: 128
    mini_batch_size: 4
    gradient_accumulation_steps: 1
training:
  desc: null
  value:
    num_epochs: 100
data:
  desc: null
  value:
    path: data/stock_data.csv
openai:
  desc: null
  value:
    model: gpt-3.5-turbo
    max_tokens: 100
    temperature: 0.7
    detection_phrase: insider trading detected
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722887151
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 95
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 95
      - 98
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.5
      6: 4.43.4
      8:
      - 5
      13: linux-x86_64
