wandb:
  project_name: "collaborative-stegosystem"
  entity: "chansmi"

env:
  max_rounds: 10
  stocks: ['AAPL', 'GOOGL', 'MSFT', 'AMZN', 'FB']
  reward:
    correct: 1.0
    partial: 0.5
    incorrect: -0.5
  eve_penalty: 2.0

model:
  name: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  quantize: true
  save_path: "models/trained_model"
  temperature: 0.9  # Increase this value to make outputs more random
  max_new_tokens: 150
  top_p: 0.9

ppo:
  learning_rate: 1.0e-5
  batch_size: 128 
  mini_batch_size: 4
  gradient_accumulation_steps: 1

training:
  num_epochs: 100

data:
  path: "data/stock_data.csv"

openai:
  model: "gpt-3.5-turbo"
  max_tokens: 100
  temperature: 0.7
  detection_phrase: "insider trading detected"