wandb_version: 1

initial_cash:
  desc: null
  value: 1000000
stock_data_path:
  desc: null
  value: data/aggregated_snp_50_stocks.csv
alice_model:
  desc: null
  value: gpt-4o-mini
bob_model:
  desc: null
  value: gpt-4o-mini
eve_model:
  desc: null
  value: gpt-4o-mini
learning_rate:
  desc: null
  value: 3e-4
clip_param:
  desc: null
  value: 0.2
ppo_epochs:
  desc: null
  value: 10
num_mini_batch:
  desc: null
  value: 4
value_loss_coef:
  desc: null
  value: 0.5
entropy_coef:
  desc: null
  value: 0.01
max_grad_norm:
  desc: null
  value: 0.5
num_episodes:
  desc: null
  value: 1000
max_steps_per_episode:
  desc: null
  value: 252
wandb_project_name:
  desc: null
  value: Collaborative Stegosystem
results_dir:
  desc: null
  value: results/
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722346394
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 4
      - 5
      13: darwin-arm64
