alice_model: "gpt-4o-mini"
bob_model: "gpt-4o-mini"
eve_model: "gpt-4o-mini"
alice_secret: "The treasure is hidden in the old oak tree."
bob_secret: "The password to the vault is 'golden sunset'."
max_turns: 10
ppo_model: "gpt-4o-mini"
ppo_params:
  batch_size: 64
  learning_rate: 1e-5
  n_epochs: 5
num_episodes: 1000
train_frequency: 10