# Environment settings
initial_cash: 1000000
stock_data_path: "data/aggregated_snp_50_stocks.csv"

# Model settings
alice_model: "gpt-4o-mini"
bob_model: "gpt-4o-mini"
eve_model: "gpt-4o-mini"

# PPO settings
learning_rate: 3e-4
clip_param: 0.2
ppo_epochs: 10
num_mini_batch: 4
value_loss_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5

# Training settings
num_episodes: 10
max_steps_per_episode: 265  # Typical number of trading days in a year

# Wandb settings
wandb_project_name: "Collaborative Stegosystem"

# Results settings
results_dir: "results/"