wandb_version: 1

alice_model:
  desc: null
  value: gpt-4o-mini
bob_model:
  desc: null
  value: distilgpt2
eve_model:
  desc: null
  value: gpt-4o-mini
model_name:
  desc: null
  value: gpt-4o-mini
num_episodes:
  desc: null
  value: 5
turns_per_episode:
  desc: null
  value: 1
max_tokens:
  desc: null
  value: 15
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722297500
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      - 95
      2:
      - 1
      - 11
      - 49
      - 55
      - 95
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.5
      6: 4.43.3
      8:
      - 4
      - 5
      13: darwin-arm64
