wandb_version: 1

alice_secret:
  desc: null
  value: The treasure is hidden in the old oak tree.
bob_secret:
  desc: null
  value: The password to the vault is 'golden sunset'.
max_turns:
  desc: null
  value: 10
num_episodes:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1722128876
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 16
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 4
      - 5
      13: darwin-arm64
